# Generated by Django 5.2.8 on 2025-11-20 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardreport',
            name='image_path',
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='contact_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='contact_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hazardreport',
            name='hazard_type',
            field=models.CharField(choices=[('FLOOD', 'Flood'), ('LANDSLIDE', 'Landslide'), ('FIRE', 'Fire'), ('TREE', 'Fallen Tree'), ('ROAD_DAMAGE', 'Road Damage'), ('BUILDING_DAMAGE', 'Building Damage'), ('UTILITY', 'Utility Hazard'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='HazardPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hazard_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='auth_app.hazardreport')),
            ],
        ),
    ]
