# Generated by Django 5.2.8 on 2025-11-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_hazardreport_image_path_hazardreport_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evacuationcenter',
            old_name='capacity_max',
            new_name='family_capacity_max',
        ),
        migrations.RemoveField(
            model_name='evacuationcenter',
            name='address',
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='barangay',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='flood_susceptibility',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='fund_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='individual_capacity_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='landslide_susceptibility',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='used_for_covid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evacuationcenter',
            name='status',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary')], default='TEMPORARY', max_length=20),
        ),
    ]
