# Generated by Django 5.2.8 on 2025-11-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_capacity_max_evacuationcenter_family_capacity_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacuationcenter',
            name='flood_susceptibility',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='evacuationcenter',
            name='landslide_susceptibility',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='Low', max_length=10),
        ),
    ]
