# Generated by Django 5.2.8 on 2025-11-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_evacuationcenter_flood_susceptibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evacuationlog',
            name='center',
        ),
        migrations.RemoveField(
            model_name='evacuationlog',
            name='reporting_staff',
        ),
        migrations.DeleteModel(
            name='EvacuationCenter',
        ),
        migrations.DeleteModel(
            name='EvacuationLog',
        ),
    ]
