# Generated by Django 5.2.8 on 2025-11-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_evacuationlog_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='province',
            field=models.CharField(blank=True, default='Oriental Mindoro', max_length=150, null=True),
        ),
    ]
