# Generated by Django 5.2.8 on 2025-11-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_barangay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangay',
            old_name='municipality_id',
            new_name='municipality',
        ),
    ]
