# Generated by Django 5.2.8 on 2026-02-09 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_customuser_is_approved'),
        ('evac_app', '0006_alter_evacuationlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='evac_app.evacuationcenter'),
        ),
    ]
