# Generated by Django 5.2.8 on 2026-02-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_hazardreport_created_at_hazardreport_reporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20),
        ),
    ]
