# Generated by Django 5.2.8 on 2026-02-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_customuser_assigned_center'),
        ('auth_app', '0011_alter_hazardreport_status'),
    ]

    operations = [
    ]
