# Generated by Django 5.2.8 on 2026-02-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_merge_20260210_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gislayer',
            name='geojson_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='hazardreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DISMISSED', 'Dismissed')], default='REPORTED', max_length=20),
        ),
    ]
