# Generated by Django 5.2.8 on 2026-02-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_alter_gislayer_geojson_data_and_more'),
        ('auth_app', '0013_alter_hazardreport_status'),
    ]

    operations = [
    ]
