# Generated by Django 5.2.8 on 2026-10-02 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardreport',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Pending'), ('APPROVED', 'Approved'), ('DISMISSED', 'Dismissed')], default='REPORTED', max_length=20),
        ),
        migrations.CreateModel(
            name='HazardReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('DISMISSED', 'Dismissed'), ('REPORTED', 'Marked as pending'), ('DELETED', 'Deleted')], db_index=True, max_length=12)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('acted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acted_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('acted_by_role', models.CharField(blank=True, default='', max_length=50)),
                ('report_ref_id', models.PositiveIntegerField(db_index=True)),
                ('report_title', models.CharField(blank=True, default='', max_length=255)),
                ('report_hazard_type', models.CharField(blank=True, default='', max_length=100)),
                ('report_severity', models.CharField(blank=True, default='', max_length=20)),
                ('report_address', models.CharField(blank=True, default='', max_length=500)),
                ('report_description', models.TextField(blank=True, default='')),
                ('reporter_name', models.CharField(blank=True, default='', max_length=255)),
                ('municipality_name', models.CharField(blank=True, default='', max_length=255)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_report_actions', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_logs', to='auth_app.municipality')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='auth_app.hazardreport')),
            ],
            options={
                'ordering': ['-acted_at', '-id'],
                'indexes': [models.Index(fields=['municipality', '-acted_at'], name='auth_app_ha_municip_ba65f8_idx')],
            },
        ),
    ]
