# Generated by Django 5.2.8 on 2025-11-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('temperature_2m', models.FloatField(null=True)),
                ('relative_humidity_2m', models.FloatField(null=True)),
                ('wind_speed_10m', models.FloatField(null=True)),
                ('wind_direction_10m', models.FloatField(null=True)),
                ('precipitation', models.FloatField(null=True)),
                ('pressure_msl', models.FloatField(null=True)),
                ('cloud_cover', models.FloatField(null=True)),
                ('city_count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['datetime'],
                'unique_together': {('datetime',)},
            },
        ),
    ]
