# Generated by Django 5.2.8 on 2026-09-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
