# Generated by Django 5.2.8 on 2025-11-20 12:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0005_remove_evacuationlog_center_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('barangay', models.CharField(blank=True, max_length=150, null=True)),
                ('fund_source', models.CharField(blank=True, max_length=255, null=True)),
                ('family_capacity_max', models.IntegerField(default=0)),
                ('individual_capacity_max', models.IntegerField(default=0)),
                ('used_for_covid', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('flood_susceptibility', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='Low', max_length=10)),
                ('landslide_susceptibility', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='Low', max_length=10)),
                ('status', models.CharField(choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary')], default='TEMPORARY', max_length=20)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='EvacuationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('families_in', models.IntegerField(default=0)),
                ('individuals_in', models.IntegerField(default=0)),
                ('families_out', models.IntegerField(default=0)),
                ('individuals_out', models.IntegerField(default=0)),
                ('vulnerable_individuals', models.IntegerField(default=0)),
                ('total_current', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evac_app.evacuationcenter')),
                ('reporting_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
