# Generated by Django 5.2.8 on 2025-11-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationcenter',
            name='province',
            field=models.CharField(default='Oriental Mindoro', max_length=100),
        ),
    ]
