# Generated by Django 5.2.8 on 2025-11-26 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_barangay'),
        ('evac_app', '0002_evacuationcenter_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacuationcenter',
            name='barangay',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.barangay'),
        ),
    ]
