# Generated by Django 5.2.8 on 2026-01-31 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_rename_municipality_id_barangay_municipality'),
        ('evac_app', '0003_alter_evacuationcenter_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacuationcenter',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.barangay'),
        ),
    ]
