# Generated by Django 5.2.8 on 2026-02-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac_app', '0004_alter_evacuationcenter_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacuationcenter',
            name='flood_susceptibility',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='evacuationcenter',
            name='landslide_susceptibility',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
    ]
