# Generated by Django 5.2.8 on 2026-02-09 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac_app', '0005_alter_evacuationcenter_flood_susceptibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evacuationlog',
            options={'ordering': ['-date_recorded', '-id']},
        ),
        migrations.AddIndex(
            model_name='evacuationlog',
            index=models.Index(fields=['center', 'date_recorded'], name='evac_app_ev_center__5346fe_idx'),
        ),
    ]
