# Generated by Django 5.2.8 on 2026-02-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac_app', '0006_alter_evacuationlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationlog',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evacuationlog',
            name='lactating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evacuationlog',
            name='pregnant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evacuationlog',
            name='pwd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evacuationlog',
            name='seniors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evacuationlog',
            name='total_current_families',
            field=models.IntegerField(default=0),
        ),
    ]
