# Generated by Django 5.2.8 on 2026-02-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evac_app', '0007_evacuationlog_children_evacuationlog_lactating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evacuationlog',
            old_name='children',
            new_name='children_count',
        ),
        migrations.RenameField(
            model_name='evacuationlog',
            old_name='lactating',
            new_name='lactating_count',
        ),
        migrations.RenameField(
            model_name='evacuationlog',
            old_name='pregnant',
            new_name='pregnant_count',
        ),
        migrations.RenameField(
            model_name='evacuationlog',
            old_name='pwd',
            new_name='pwd_count',
        ),
        migrations.RenameField(
            model_name='evacuationlog',
            old_name='seniors',
            new_name='senior_count',
        ),
    ]
