# Generated by Django 5.2.8 on 2026-04-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac_app', '0008_rename_children_evacuationlog_children_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationcenter',
            name='shelter_category',
            field=models.CharField(choices=[('INSIDE_EC', 'Inside Evacuation Center'), ('OUTSIDE_EC', 'Outside Evacuation Center')], default='INSIDE_EC', max_length=20),
        ),
    ]
