# Generated by Django 5.2.8 on 2026-05-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac_app', '0009_evacuationcenter_shelter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationlog',
            name='disaster_cause',
            field=models.CharField(choices=[('TYPHOON', 'Typhoon'), ('FLOOD', 'Flood'), ('LANDSLIDE', 'Landslide'), ('EARTHQUAKE', 'Earthquake'), ('FIRE', 'Fire'), ('VOLCANIC_ACTIVITY', 'Volcanic Activity'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
