# Generated by Django 5.2.8 on 2026-05-29 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac_app', '0010_evacuationlog_disaster_cause'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evacuee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(default=0)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('family_head_name', models.CharField(blank=True, max_length=150)),
                ('family_number', models.CharField(blank=True, max_length=50)),
                ('is_child', models.BooleanField(default=False)),
                ('is_senior', models.BooleanField(default=False)),
                ('is_pwd', models.BooleanField(default=False)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('is_lactating', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuees', to='evac_app.evacuationcenter')),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evacuees', to='evac_app.evacuationlog')),
            ],
        ),
    ]
