# Generated by Django 5.2.8 on 2026-05-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac_app', '0011_evacuee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evacuee',
            name='family_number',
        ),
        migrations.AddField(
            model_name='evacuee',
            name='is_family_head',
            field=models.BooleanField(default=False),
        ),
    ]
