# Generated by Django 5.2.8 on 2026-05-31 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac_app', '0012_remove_evacuee_family_number_evacuee_is_family_head'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('WATER', 'Water'), ('CLOTHING', 'Clothing'), ('MEDICAL', 'Medical'), ('HYGIENE', 'Hygiene'), ('BEDDING', 'Bedding'), ('BABY_SUPPLIES', 'Baby Supplies'), ('OTHER', 'Other')], max_length=30)),
                ('quantity_needed', models.PositiveIntegerField(default=0)),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_needs', to='evac_app.evacuationcenter')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_needs_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=150)),
                ('donor_contact', models.CharField(blank=True, max_length=50)),
                ('donor_address', models.TextField(blank=True)),
                ('item_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('status', models.CharField(choices=[('PLEDGED', 'Pledged'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='evac_app.evacuationcenter')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_received', to=settings.AUTH_USER_MODEL)),
                ('need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='evac_app.donationneed')),
            ],
        ),
    ]
