# Generated by Django 5.2.8 on 2026-08-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac_app', '0014_donationdistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuee',
            name='reason_for_evacuation',
            field=models.CharField(choices=[('TYPHOON', 'Typhoon'), ('FLOOD', 'Flood'), ('LANDSLIDE', 'Landslide'), ('EARTHQUAKE', 'Earthquake'), ('FIRE', 'Fire'), ('VOLCANIC_ACTIVITY', 'Volcanic Activity'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
