# Generated by Django 5.2.8 on 2026-08-17 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac_app', '0015_evacuee_reason_for_evacuation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive reasons are hidden from the staff dropdown but kept for existing records.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='evacuationlog',
            name='disaster_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cause', to='evac_app.evacuationreason'),
        ),
        migrations.AlterField(
            model_name='evacuee',
            name='reason_for_evacuation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evacuees', to='evac_app.evacuationreason'),
        ),
    ]
