# Generated by Django 5.2.8 on 2026-08-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac_app', '0016_evacuationreason_alter_evacuationlog_disaster_cause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationlog',
            name='children_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evacuationlog',
            name='lactating_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evacuationlog',
            name='pregnant_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evacuationlog',
            name='pwd_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evacuationlog',
            name='senior_out',
            field=models.IntegerField(default=0),
        ),
    ]
